---
title: metaLAB (at) Harvard
timezone: UTC
collections:
  events:
    title: Events
    output: true
    permalink: "/events/:path/"
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  publications:
    title: Publications
    output: true
    permalink: "/publications/:path/"
  teaching:
    title: Teaching
    output: true
    permalink: "/teaching/:path/"
  uploads:
    title: Uploads
    output: true
email: info@metalab.harvard.edu
description: "***\n"
baseurl: ''
url: localhost:4000
twitter_username: metalabharvard
github_username: metalabharvard
markdown: kramdown
theme: minima
